#!/usr/bin/env bash
# Refresh the reachable-node set used by addrman-health.html.
#
# The page cannot fetch this itself: bitnod.es serves no Access-Control-Allow-Origin
# header, so a browser blocks the cross-origin request from any origin, file://
# included. This script does the download and writes reachable-data.js beside the
# dashboard; the page loads that with a plain <script src>, which CORS does not gate.
#
#   ./refresh-reachable.sh            # newest CSV listed on the explorer page
#   ./refresh-reachable.sh 2026-08-11 # a specific day
#
# Cron it if you want it current:
#   17 6 * * *  ~/Projects/bitcoin-core-notes/dashboards/refresh-reachable.sh >/dev/null 2>&1
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/reachable-data.js"
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36"
BASE="https://bitnod.es"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

if [ $# -ge 1 ]; then
  PATH_CSV="/csv/bitcoin_nodes_$1.csv"
else
  echo "finding the newest daily CSV…" >&2
  curl -sSL -A "$UA" "$BASE/node_explorer.php" -o "$TMP/explorer.html"
  PATH_CSV="$(grep -oE '/csv/bitcoin_nodes_[0-9-]+\.csv' "$TMP/explorer.html" | sort -u | tail -1)"
  [ -n "$PATH_CSV" ] || { echo "no CSV link found on the explorer page" >&2; exit 1; }
fi

echo "downloading $BASE$PATH_CSV" >&2
curl -sSfL -A "$UA" "$BASE$PATH_CSV" -o "$TMP/nodes.csv"

# Keep only the three columns the dashboard uses; the full export is ~6 MB, most
# of it country / isp / user_agent that nothing here reads.
python3 - "$TMP/nodes.csv" "$OUT" "$BASE$PATH_CSV" <<'PY'
import csv, json, sys, datetime
src, out, url = sys.argv[1], sys.argv[2], sys.argv[3]
rows = list(csv.DictReader(open(src, newline='')))
if not rows:
    sys.exit('CSV had no rows')
need = ('export_date', 'ip_address', 'port')
missing = [c for c in need if c not in rows[0]]
if missing:
    sys.exit('CSV is missing expected column(s): %s — got %s'
             % (', '.join(missing), ', '.join(rows[0].keys())))
lines = ['export_date,ip_address,port']
for r in rows:
    lines.append('%s,%s,%s' % (r['export_date'], r['ip_address'], r['port']))
payload = {
    'source':  url,
    'fetched': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    'rows':    len(rows),
    'csv':     '\n'.join(lines),
}
with open(out, 'w') as f:
    f.write('/* generated by refresh-reachable.sh — do not edit */\n')
    f.write('window.REACHABLE=' + json.dumps(payload) + ';\n')
print('wrote %s  (%d rows)' % (out, len(rows)), file=sys.stderr)
PY

ls -lh "$OUT" | awk '{print "  " $5 "  " $9}'
