#!/usr/bin/env bash
# Refresh the Tor exit-relay IP set used by section 1.5 of the dashboard.
#
# Same reason refresh-reachable.sh exists: check.torproject.org sends no
# Access-Control-Allow-Origin header, so a browser blocks the cross-origin fetch
# from any origin, file:// included. This writes tor-exit-data.js beside the
# dashboard and the page loads it with a plain <script src>, which CORS does not gate.
#
#   ./refresh-tor-exits.sh
#
# The bulk list holds exits that permit exiting to check.torproject.org, which is
# the usual definition of "is this IP a Tor exit" but not every exit address a relay
# has ever used. Onionoo's exit_addresses field is the fuller answer if this ever
# needs to be exact.
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/tor-exit-data.js"
URL="https://check.torproject.org/torbulkexitlist"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

echo "downloading $URL" >&2
curl -sSfL "$URL" -o "$TMP/exits.txt"

python3 - "$TMP/exits.txt" "$OUT" "$URL" <<'PY'
import sys, json, re, datetime
src, out, url = sys.argv[1], sys.argv[2], sys.argv[3]
ips = []
seen = set()
for line in open(src):
    ip = line.strip()
    if not ip or ip.startswith('#'):
        continue
    # the list is one bare address per line; reject anything else rather than
    # shipping junk the page would silently fail to match
    if not re.fullmatch(r'[0-9a-fA-F:.]+', ip):
        sys.exit('unexpected line in exit list: %r' % line[:80])
    if ip not in seen:
        seen.add(ip); ips.append(ip)
if not ips:
    sys.exit('exit list was empty')
payload = {
    'source':  url,
    'fetched': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ'),
    'count':   len(ips),
    'ips':     '\n'.join(ips),
}
with open(out, 'w') as f:
    f.write('/* generated by refresh-tor-exits.sh — do not edit */\n')
    f.write('window.TOR_EXITS=' + json.dumps(payload) + ';\n')
print('wrote %s  (%d exit IPs)' % (out, len(ips)), file=sys.stderr)
PY

ls -lh "$OUT" | awk '{print "  " $5 "  " $9}'
