#!/usr/bin/env bash
# Refresh the sample peers.dat behind the "Load sample peers.dat" button.
#
# Takes the newest weekly snapshot from peer-observer's hal node, decompresses
# the .zst (browsers cannot read zstd) and writes it gzipped + base64 into
# sample-peers-data.js. Wrapped as a script for the same reason as
# reachable-data.js: the page loads it with a <script src>, which also works
# when index.html is opened from file://, where fetch() is blocked.
#
#   ./refresh-sample-peers.sh
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/sample-peers-data.js"
BASE="https://demo.peer.observer/peers-dat-snapshots/hal/"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

NAME="$(curl -sSfL "$BASE" | grep -oE 'peers-[0-9]{8}-hal\.dat\.zst' | sort -u | tail -n1)"
[ -n "$NAME" ] || { echo "no snapshot found at $BASE" >&2; exit 1; }

echo "downloading $BASE$NAME" >&2
curl -sSfL "$BASE$NAME" -o "$TMP/peers.dat.zst"
zstd -dq "$TMP/peers.dat.zst" -o "$TMP/peers.dat"
gzip -9n "$TMP/peers.dat"

python3 - "$TMP/peers.dat.gz" "$OUT" "${NAME%.zst}" "$BASE$NAME" <<'PY'
import sys, json, base64
src, out, name, url = sys.argv[1:5]
payload = {
    'name':   name,
    'source': url,
    'gz':     base64.b64encode(open(src, 'rb').read()).decode(),
}
with open(out, 'w') as f:
    f.write('/* generated by refresh-sample-peers.sh — do not edit */\n')
    f.write('window.SAMPLE_PEERS=' + json.dumps(payload) + ';\n')
print('wrote %s  (%s)' % (out, name), file=sys.stderr)
PY

ls -lh "$OUT" | awk '{print "  " $5 "  " $9}'
